### ISSUE TITLE
Update standard file for PHP 7 return type hints.

### ISSUE THREAD

**Issue by tburry** [vanilla/standards#12]
Consider the following code:

```php
public function getGlobalKey(): string {
```

The `(): string` type hint [should be acceptable](https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#45-method-and-function-arguments), but gives an error asking for a space before the colon.

It's possible that this can be fixed by bringing in an already coded standard library and subclassing it.

**Comment by charrondev** [comment]
This should be resolved with our update to phpcs 3.0
