### ISSUE TITLE
DocBlock parameters should not be aligned to each other.

### ISSUE THREAD

**Issue by charrondev** [vanilla/standards#8]
Vanilla tends not to do variable alignment. It leads to noisier diffs, and is a bit of a PITA. Most our code base doesn't do this. I don't really have any skin in this, but @linc seems to the think we should not enforce this.

Rules starts [here](https://github.com/vanilla/standards/blob/master/code-sniffer/Vanilla/Sniffs/Commenting/FunctionCommentSniff.php#L420).

**Comment by linc** [comment]
closed by https://github.com/vanilla/standards/pull/14
